name: Upload Python Package with Tag Release

on:
  push:
    tags:
      - '*'

jobs:
  build_and_deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies and build package
        run: |
          python -m pip install --upgrade pip
          pip install wheel Cython setuptools
          python setup.py bdist_wheel

      - name: Check if package is built
        run: |
          if [[ ! -f dist/*.whl ]]; then
            echo "No wheel file found in dist directory"
            exit 1
          fi
        shell: bash

      - name: Read release notes
        id: read_notes
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const notes = fs.readFileSync('notes.txt', 'utf8');
            return notes;


      - name: Create Release
        id: create_release
        if: success()
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}  # 使用推送的标签名称
          release_name: Release ${{ github.ref_name }}
          body: ${{ steps.read_notes.outputs.result }}
          files: dist/*

      - name: Publish to PyPI
        if: success()
        uses: pypa/gh-action-pypi-publish@v1.9.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
